FROM python:3.11-slim

# Config
ENV PYTHONUNBUFFERED=1
WORKDIR /app

# Deps
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Code
COPY . .

# Launch Command (Runs the Supplier Service)
CMD ["python", "supplier_agent_service.py"]